version: 1.0.0
services:
  - php:
      version: 8.2

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - echo "Build Executed"
post-deploy:
  steps:
    - setup:
        type: script
        script:
         - source $SOURCE_DIR/setup.sh
